### ISSUE TITLE
Redefine frame value inside operator

### ISSUE THREAD

**Issue by demensky** [timdp/swirly#35]
```
---1-----------3----5--------------|

> mergeMap((x) => `y---y---y-|`)
y := x*2

   a---a---a-|
   a := 10

               b---b---b-|
               b := 30

                     c---c---c-|
                     c := 50

---a---a---a---b---b-c-b-c---c-----|
a := 10
b := 30
c := 50
```

### Actual behavior

![](https://user-images.githubusercontent.com/10235949/176730690-6c537984-a5a6-431a-82be-5582c312487b.png)

### Expected behavior

![](https://user-images.githubusercontent.com/10235949/176730890-66bb6341-d016-424f-9e46-f53f7a0dc161.png)

**Comment by timdp** [comment]
Good idea! Thanks for the clear example as well.

I've added this as of v0.20.0. Feel free to reopen if it's not working as intended.

**Comment by demensky** [comment]
Thank you very much! I am trying to move rxjs marble to SVG.
