### ISSUE TITLE
Missing left padding in diagram inside operator

### ISSUE THREAD

**Issue by demensky** [timdp/swirly#37]
```
-1-2-3-4-5-|

> someOperator(() => `a|`)

-1-2-3-4-5-|
```

### Actual behavior

<img src="https://user-images.githubusercontent.com/10235949/176779949-d7d24faf-16d3-4a25-baed-f7390178c6d2.png" width="430" height="260" />

Expected behavior

<img src="https://user-images.githubusercontent.com/10235949/176780045-80e79f68-cba2-44d9-934f-0b34d07f511e.png" width="430" height="260" />

**Comment by timdp** [comment]
I've been meaning to look into that. Thanks again for creating a clear issue!

**Comment by timdp** [comment]
This should now be fixed on swirly.dev and will be included in the next release.

**Comment by timdp** [comment]
As a sidenote, the fix also deals with:

- the same issue with "regular" observables rather than ones inside operators;
- the right side of an observable's arrowhead being cut off inside operators.
