### ISSUE TITLE
Operator box width

### ISSUE THREAD

**Issue by niklas-wortmann** [timdp/swirly#4]
Right now the Operator Box width is automatically set according to the width of the observables. At least that's what it looks like?!

It could be handy to specify the width for that, for Example for `EMPTY`

**Comment by timdp** [comment]
Yeah, this is a todo. I'm pretty sure it can already be achieved by setting `duration` on the stream in the parsed diagram object though. (Or via the CLI by using YAML input instead of text.)

**Comment by timdp** [comment]
You can now set `minimum_width` and `minimum_height` styles. Operators will stretch to fill the full width.
