### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by hennihaus** [timdp/swirly#49]
Hello @timdp, how can I use negative numbers in this editor to produce something similar as shown below?

<img width="342" alt="Bildschirmfoto 2024-03-23 um 12 07 04" src="https://github.com/timdp/swirly/assets/47771386/95c26758-0bd5-4a1f-a2d2-fef93bf1fbd9">

**Comment by timdp** [comment]
The fact that those are numbers don't really matter. Events can take any text-based value/label. The default is the single-letter ID in the observable itself; you can override each one using the `:=` operator. For example:

```
--x--y--|
x := 42
y := -1
```

**Comment by hennihaus** [comment]
Thank you for the quick answer. I had an empty line between the marble and numbers. That was my error.
