### ISSUE TITLE
Make toOperatorSpec and toStreamSpec part of public API

### ISSUE THREAD

**Issue by sengmann** [timdp/swirly#7]
It would be nice to be able to access the two functions mentioned in the title as part of the public interface. I have written a small  [library](https://github.com/sengmann/swirly-diagram-testrunner) to use your project to generate diagrams in Unit Tests.

**Comment by timdp** [comment]
Love the library. It actually looks a lot like the feature that @niklas-wortmann removed from the RxJS repo when introducing Swirly there.

I'll look into exposing the factory functions in a consistent manner. Might end up changing the API a little bit. I'll keep you posted!

**Comment by timdp** [comment]
Well, that took me longer than expected. However, as of v0.15.0, the parser package exports the functions you need. They've been renamed but the signature hasn't changed:

```ts
export {
  parseMarbleDiagramSpecification,
  createDiagramSpecification,
  createOperatorSpecification,
  createStreamSpecification
}
```
